FROM python

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ALLOWED_HOSTS localhost,127.0.0.1

WORKDIR /app
COPY ./requirements.txt /app
COPY . . 

RUN pip install -r requirements.txt
